---
title: "ASSIGNMENT #4: FINAL PROJECT"
author: "Addison Playo & Juan Pedro Bretti Mandarano"
date: "JAN/07/2021"
output:
  html_document:
  code_folding: show
toc: true
toc_float:
  collapsed: false
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Start

Set the folder (path) that contains this R file as the working directory

```{r}
library(tidyverse)
library(skimr)
library(ggpmisc)
library(lubridate)
library(ggridges)
library(ggalluvial)
library(readxl)
```

## Load data

Read the raw data from the CSV file.

```{r}
df_data <- read_excel(path='source/WDIEXCEL.xlsx', sheet='Data')
df_country <- read_excel(path='source/WDIEXCEL.xlsx', sheet='Country')
```

```{r}
df_data <- df_data %>% 
  pivot_longer(starts_with(c('1', '2')), names_to='Year', values_to='Value') %>% 
  filter(!is.na(`Value`))
```

## Quick EDA

```{r}
skim(df_data)
```

```{r}
skim(df_country)
```

```{r}
table(df_data['Indicator Name']) %>% 
  as.data.frame() %>% 
  arrange(desc(Freq)) %>% 
  filter(str_detect(Var1, regex('child', ignore_case = T))) %>% 
  filter(str_detect(Var1, regex('school', ignore_case = T)))
```


```{r}
df_data %>% 
  filter(`Indicator Name` %in% c('Children out of school, primary', 'Children out of school, primary, female', 'Children out of school, primary, male')) %>% 
  group_by(`Indicator Name`, `Year`) %>% 
  summarise(`Value`=mean(`Value`)) %>% 
  ggplot() +
  geom_point(aes(x=Year, y=Value, color=`Indicator Name`))
```





